// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatMessage is an encrypted text message sent during Stage 4 of the handshake.
// The ciphertext contains a serialized ChatPlaintext encrypted with AES-256-GCM
// using the session key derived during the handshake.
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Random UUID (16 bytes) for ACK correlation
	// Allows the sender to match acknowledgments to sent messages
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// AES-256-GCM encrypted payload containing serialized ChatPlaintext
	// Encrypted with the session key established during handshake
	Ciphertext []byte `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// GCM nonce (12 bytes), must be unique per message
	// Never reuse a nonce with the same key
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Unix milliseconds when the message was sent
	// Used for ordering messages in the UI
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *ChatMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *ChatMessage) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ChatAck confirms successful receipt and decryption of a ChatMessage.
// The message_hash proves the recipient successfully decrypted the message.
type ChatAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the message_id being acknowledged
	// Allows sender to correlate ACKs to sent messages
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// SHA-256(plaintext) to confirm correct decryption
	// Proves the message was decrypted successfully, not just received
	MessageHash   []byte `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatAck) Reset() {
	*x = ChatAck{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAck) ProtoMessage() {}

func (x *ChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAck.ProtoReflect.Descriptor instead.
func (*ChatAck) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatAck) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *ChatAck) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

// ChatTyping indicates the sender's typing status.
// Used to show "user is typing..." indicators in the UI.
type ChatTyping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true = started typing, false = stopped typing
	// Should be sent when typing starts and after a brief pause
	IsTyping      bool `protobuf:"varint,1,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTyping) Reset() {
	*x = ChatTyping{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTyping) ProtoMessage() {}

func (x *ChatTyping) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTyping.ProtoReflect.Descriptor instead.
func (*ChatTyping) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatTyping) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

// ChatEnvelope wraps all chat protocol messages.
// This allows multiplexing different message types over the same stream.
type ChatEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatEnvelope_Message
	//	*ChatEnvelope_Ack
	//	*ChatEnvelope_Typing
	Payload       isChatEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEnvelope) Reset() {
	*x = ChatEnvelope{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEnvelope) ProtoMessage() {}

func (x *ChatEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEnvelope.ProtoReflect.Descriptor instead.
func (*ChatEnvelope) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatEnvelope) GetPayload() isChatEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatEnvelope) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatEnvelope) GetAck() *ChatAck {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ChatEnvelope) GetTyping() *ChatTyping {
	if x != nil {
		if x, ok := x.Payload.(*ChatEnvelope_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

type isChatEnvelope_Payload interface {
	isChatEnvelope_Payload()
}

type ChatEnvelope_Message struct {
	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatEnvelope_Ack struct {
	Ack *ChatAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ChatEnvelope_Typing struct {
	Typing *ChatTyping `protobuf:"bytes,3,opt,name=typing,proto3,oneof"`
}

func (*ChatEnvelope_Message) isChatEnvelope_Payload() {}

func (*ChatEnvelope_Ack) isChatEnvelope_Payload() {}

func (*ChatEnvelope_Typing) isChatEnvelope_Payload() {}

// ChatPlaintext is the decrypted content of ChatMessage.ciphertext.
// This message is serialized and encrypted, never sent in the clear.
type ChatPlaintext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UTF-8 message content, maximum 4096 bytes
	// Longer messages should be split by the sender
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Sender's local timestamp (Unix milliseconds)
	// May differ from ChatMessage.timestamp due to network delay
	SentAt        int64 `protobuf:"varint,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPlaintext) Reset() {
	*x = ChatPlaintext{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPlaintext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPlaintext) ProtoMessage() {}

func (x *ChatPlaintext) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPlaintext.ProtoReflect.Descriptor instead.
func (*ChatPlaintext) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatPlaintext) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatPlaintext) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\fmymonad.chat\"\x80\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"K\n" +
	"\aChatAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\fR\vmessageHash\")\n" +
	"\n" +
	"ChatTyping\x12\x1b\n" +
	"\tis_typing\x18\x01 \x01(\bR\bisTyping\"\xaf\x01\n" +
	"\fChatEnvelope\x125\n" +
	"\amessage\x18\x01 \x01(\v2\x19.mymonad.chat.ChatMessageH\x00R\amessage\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.mymonad.chat.ChatAckH\x00R\x03ack\x122\n" +
	"\x06typing\x18\x03 \x01(\v2\x18.mymonad.chat.ChatTypingH\x00R\x06typingB\t\n" +
	"\apayload\"<\n" +
	"\rChatPlaintext\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\x03R\x06sentAtB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_proto_goTypes = []any{
	(*ChatMessage)(nil),   // 0: mymonad.chat.ChatMessage
	(*ChatAck)(nil),       // 1: mymonad.chat.ChatAck
	(*ChatTyping)(nil),    // 2: mymonad.chat.ChatTyping
	(*ChatEnvelope)(nil),  // 3: mymonad.chat.ChatEnvelope
	(*ChatPlaintext)(nil), // 4: mymonad.chat.ChatPlaintext
}
var file_chat_proto_depIdxs = []int32{
	0, // 0: mymonad.chat.ChatEnvelope.message:type_name -> mymonad.chat.ChatMessage
	1, // 1: mymonad.chat.ChatEnvelope.ack:type_name -> mymonad.chat.ChatAck
	2, // 2: mymonad.chat.ChatEnvelope.typing:type_name -> mymonad.chat.ChatTyping
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_chat_proto_msgTypes[3].OneofWrappers = []any{
		(*ChatEnvelope_Message)(nil),
		(*ChatEnvelope_Ack)(nil),
		(*ChatEnvelope_Typing)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
