// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: discovery.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiscoveryCommit is sent first by both parties in the LSH discovery protocol.
// This implements a commitment scheme to prevent cheating where a peer could
// adjust their signature after seeing the other peer's signature.
type DiscoveryCommit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256(signature || salt), 32 bytes
	// The commitment hides the signature until both parties have committed
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// Unix milliseconds, for replay protection (±5s window)
	// Prevents replay attacks by ensuring commits are fresh
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Sender's libp2p peer ID
	// Identifies which peer sent this commit
	PeerId        []byte `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryCommit) Reset() {
	*x = DiscoveryCommit{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryCommit) ProtoMessage() {}

func (x *DiscoveryCommit) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryCommit.ProtoReflect.Descriptor instead.
func (*DiscoveryCommit) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryCommit) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *DiscoveryCommit) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DiscoveryCommit) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// DiscoveryReveal is sent after both commits are exchanged.
// Reveals the actual LSH signature and salt, allowing verification
// that the commitment was honest.
type DiscoveryReveal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full LSH signature (N bits, typically 256)
	// This is the locality-sensitive hash of the peer's monad
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Random salt used in commitment (minimum 16 bytes, high-entropy)
	// Must match the salt used when computing the commitment
	Salt          []byte `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryReveal) Reset() {
	*x = DiscoveryReveal{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryReveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryReveal) ProtoMessage() {}

func (x *DiscoveryReveal) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryReveal.ProtoReflect.Descriptor instead.
func (*DiscoveryReveal) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryReveal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DiscoveryReveal) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

// DiscoveryReject indicates protocol failure during LSH discovery.
type DiscoveryReject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason for rejection. Must be one of:
	// - "commitment_mismatch": The revealed signature/salt doesn't match the commitment
	// - "stale_timestamp": The commit timestamp is outside the ±5s validity window
	// - "invalid_salt": The salt is too short (< 16 bytes) or not high-entropy
	// - "malformed_signature": The signature is invalid or wrong length
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryReject) Reset() {
	*x = DiscoveryReject{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryReject) ProtoMessage() {}

func (x *DiscoveryReject) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryReject.ProtoReflect.Descriptor instead.
func (*DiscoveryReject) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoveryReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\x11mymonad.discovery\"h\n" +
	"\x0fDiscoveryCommit\x12\x1e\n" +
	"\n" +
	"commitment\x18\x01 \x01(\fR\n" +
	"commitment\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\fR\x06peerId\"C\n" +
	"\x0fDiscoveryReveal\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\")\n" +
	"\x0fDiscoveryReject\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_discovery_proto_goTypes = []any{
	(*DiscoveryCommit)(nil), // 0: mymonad.discovery.DiscoveryCommit
	(*DiscoveryReveal)(nil), // 1: mymonad.discovery.DiscoveryReveal
	(*DiscoveryReject)(nil), // 2: mymonad.discovery.DiscoveryReject
}
var file_discovery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
