// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: handshake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_ATTESTATION_REQUEST   MessageType = 0
	MessageType_ATTESTATION_RESPONSE  MessageType = 1
	MessageType_VECTOR_MATCH_REQUEST  MessageType = 2
	MessageType_VECTOR_MATCH_RESPONSE MessageType = 3
	MessageType_DEALBREAKER_REQUEST   MessageType = 4
	MessageType_DEALBREAKER_RESPONSE  MessageType = 5
	MessageType_CHAT_MESSAGE          MessageType = 6
	MessageType_UNMASK_REQUEST        MessageType = 7
	MessageType_UNMASK_RESPONSE       MessageType = 8
	MessageType_REJECT                MessageType = 9
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "ATTESTATION_REQUEST",
		1: "ATTESTATION_RESPONSE",
		2: "VECTOR_MATCH_REQUEST",
		3: "VECTOR_MATCH_RESPONSE",
		4: "DEALBREAKER_REQUEST",
		5: "DEALBREAKER_RESPONSE",
		6: "CHAT_MESSAGE",
		7: "UNMASK_REQUEST",
		8: "UNMASK_RESPONSE",
		9: "REJECT",
	}
	MessageType_value = map[string]int32{
		"ATTESTATION_REQUEST":   0,
		"ATTESTATION_RESPONSE":  1,
		"VECTOR_MATCH_REQUEST":  2,
		"VECTOR_MATCH_RESPONSE": 3,
		"DEALBREAKER_REQUEST":   4,
		"DEALBREAKER_RESPONSE":  5,
		"CHAT_MESSAGE":          6,
		"UNMASK_REQUEST":        7,
		"UNMASK_RESPONSE":       8,
		"REJECT":                9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_handshake_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_handshake_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{0}
}

// HandshakeEnvelope wraps all handshake messages.
type HandshakeEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=handshake.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeEnvelope) Reset() {
	*x = HandshakeEnvelope{}
	mi := &file_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeEnvelope) ProtoMessage() {}

func (x *HandshakeEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeEnvelope.ProtoReflect.Descriptor instead.
func (*HandshakeEnvelope) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeEnvelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ATTESTATION_REQUEST
}

func (x *HandshakeEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HandshakeEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AttestationRequestPayload is the payload for ATTESTATION_REQUEST.
type AttestationRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Challenge     string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"` // Hashcash challenge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationRequestPayload) Reset() {
	*x = AttestationRequestPayload{}
	mi := &file_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequestPayload) ProtoMessage() {}

func (x *AttestationRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequestPayload.ProtoReflect.Descriptor instead.
func (*AttestationRequestPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationRequestPayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AttestationRequestPayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AttestationRequestPayload) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

// AttestationResponsePayload is the payload for ATTESTATION_RESPONSE.
type AttestationResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Solution      string                 `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"` // Hashcash solution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationResponsePayload) Reset() {
	*x = AttestationResponsePayload{}
	mi := &file_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponsePayload) ProtoMessage() {}

func (x *AttestationResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponsePayload.ProtoReflect.Descriptor instead.
func (*AttestationResponsePayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *AttestationResponsePayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AttestationResponsePayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AttestationResponsePayload) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

// VectorMatchRequestPayload is the payload for VECTOR_MATCH_REQUEST.
type VectorMatchRequestPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	EncryptedMonad []byte                 `protobuf:"bytes,2,opt,name=encrypted_monad,json=encryptedMonad,proto3" json:"encrypted_monad,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VectorMatchRequestPayload) Reset() {
	*x = VectorMatchRequestPayload{}
	mi := &file_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorMatchRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMatchRequestPayload) ProtoMessage() {}

func (x *VectorMatchRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMatchRequestPayload.ProtoReflect.Descriptor instead.
func (*VectorMatchRequestPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *VectorMatchRequestPayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *VectorMatchRequestPayload) GetEncryptedMonad() []byte {
	if x != nil {
		return x.EncryptedMonad
	}
	return nil
}

// VectorMatchResponsePayload is the payload for VECTOR_MATCH_RESPONSE.
type VectorMatchResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"` // Score >= threshold (score not revealed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorMatchResponsePayload) Reset() {
	*x = VectorMatchResponsePayload{}
	mi := &file_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorMatchResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMatchResponsePayload) ProtoMessage() {}

func (x *VectorMatchResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMatchResponsePayload.ProtoReflect.Descriptor instead.
func (*VectorMatchResponsePayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *VectorMatchResponsePayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *VectorMatchResponsePayload) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

// DealBreakerRequestPayload is the payload for DEALBREAKER_REQUEST.
type DealBreakerRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*DealBreakerQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealBreakerRequestPayload) Reset() {
	*x = DealBreakerRequestPayload{}
	mi := &file_handshake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreakerRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreakerRequestPayload) ProtoMessage() {}

func (x *DealBreakerRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreakerRequestPayload.ProtoReflect.Descriptor instead.
func (*DealBreakerRequestPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{5}
}

func (x *DealBreakerRequestPayload) GetQuestions() []*DealBreakerQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

type DealBreakerQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        bool                   `protobuf:"varint,3,opt,name=answer,proto3" json:"answer,omitempty"` // Our answer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealBreakerQuestion) Reset() {
	*x = DealBreakerQuestion{}
	mi := &file_handshake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreakerQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreakerQuestion) ProtoMessage() {}

func (x *DealBreakerQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreakerQuestion.ProtoReflect.Descriptor instead.
func (*DealBreakerQuestion) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{6}
}

func (x *DealBreakerQuestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DealBreakerQuestion) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *DealBreakerQuestion) GetAnswer() bool {
	if x != nil {
		return x.Answer
	}
	return false
}

// DealBreakerResponsePayload is the payload for DEALBREAKER_RESPONSE.
type DealBreakerResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []*DealBreakerAnswer   `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	Compatible    bool                   `protobuf:"varint,2,opt,name=compatible,proto3" json:"compatible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealBreakerResponsePayload) Reset() {
	*x = DealBreakerResponsePayload{}
	mi := &file_handshake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreakerResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreakerResponsePayload) ProtoMessage() {}

func (x *DealBreakerResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreakerResponsePayload.ProtoReflect.Descriptor instead.
func (*DealBreakerResponsePayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{7}
}

func (x *DealBreakerResponsePayload) GetAnswers() []*DealBreakerAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DealBreakerResponsePayload) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

type DealBreakerAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer        bool                   `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealBreakerAnswer) Reset() {
	*x = DealBreakerAnswer{}
	mi := &file_handshake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealBreakerAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealBreakerAnswer) ProtoMessage() {}

func (x *DealBreakerAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealBreakerAnswer.ProtoReflect.Descriptor instead.
func (*DealBreakerAnswer) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{8}
}

func (x *DealBreakerAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *DealBreakerAnswer) GetAnswer() bool {
	if x != nil {
		return x.Answer
	}
	return false
}

// ChatMessagePayload is the payload for CHAT_MESSAGE.
type ChatMessagePayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	EncryptedContent []byte                 `protobuf:"bytes,2,opt,name=encrypted_content,json=encryptedContent,proto3" json:"encrypted_content,omitempty"` // Encrypted with session key
	Sequence         int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessagePayload) Reset() {
	*x = ChatMessagePayload{}
	mi := &file_handshake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessagePayload) ProtoMessage() {}

func (x *ChatMessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessagePayload.ProtoReflect.Descriptor instead.
func (*ChatMessagePayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessagePayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessagePayload) GetEncryptedContent() []byte {
	if x != nil {
		return x.EncryptedContent
	}
	return nil
}

func (x *ChatMessagePayload) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// UnmaskRequestPayload is the payload for UNMASK_REQUEST.
type UnmaskRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // Indicates ready to unmask
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmaskRequestPayload) Reset() {
	*x = UnmaskRequestPayload{}
	mi := &file_handshake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmaskRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmaskRequestPayload) ProtoMessage() {}

func (x *UnmaskRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmaskRequestPayload.ProtoReflect.Descriptor instead.
func (*UnmaskRequestPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{10}
}

func (x *UnmaskRequestPayload) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// UnmaskResponsePayload is the payload for UNMASK_RESPONSE.
type UnmaskResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Identity      *IdentityPayload       `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"` // Only set if accepted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmaskResponsePayload) Reset() {
	*x = UnmaskResponsePayload{}
	mi := &file_handshake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmaskResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmaskResponsePayload) ProtoMessage() {}

func (x *UnmaskResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmaskResponsePayload.ProtoReflect.Descriptor instead.
func (*UnmaskResponsePayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{11}
}

func (x *UnmaskResponsePayload) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UnmaskResponsePayload) GetIdentity() *IdentityPayload {
	if x != nil {
		return x.Identity
	}
	return nil
}

// IdentityPayload contains the revealed identity.
type IdentityPayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DisplayName string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Contact method (at least one required)
	Email        string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	SignalNumber string `protobuf:"bytes,3,opt,name=signal_number,json=signalNumber,proto3" json:"signal_number,omitempty"`
	MatrixId     string `protobuf:"bytes,4,opt,name=matrix_id,json=matrixId,proto3" json:"matrix_id,omitempty"`
	// Optional verification
	PgpPublicKey   []byte `protobuf:"bytes,5,opt,name=pgp_public_key,json=pgpPublicKey,proto3" json:"pgp_public_key,omitempty"`
	PgpFingerprint string `protobuf:"bytes,6,opt,name=pgp_fingerprint,json=pgpFingerprint,proto3" json:"pgp_fingerprint,omitempty"`
	// Proves contact belongs to this Ed25519 identity
	ContactSignature []byte `protobuf:"bytes,7,opt,name=contact_signature,json=contactSignature,proto3" json:"contact_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentityPayload) Reset() {
	*x = IdentityPayload{}
	mi := &file_handshake_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityPayload) ProtoMessage() {}

func (x *IdentityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityPayload.ProtoReflect.Descriptor instead.
func (*IdentityPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{12}
}

func (x *IdentityPayload) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IdentityPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityPayload) GetSignalNumber() string {
	if x != nil {
		return x.SignalNumber
	}
	return ""
}

func (x *IdentityPayload) GetMatrixId() string {
	if x != nil {
		return x.MatrixId
	}
	return ""
}

func (x *IdentityPayload) GetPgpPublicKey() []byte {
	if x != nil {
		return x.PgpPublicKey
	}
	return nil
}

func (x *IdentityPayload) GetPgpFingerprint() string {
	if x != nil {
		return x.PgpFingerprint
	}
	return ""
}

func (x *IdentityPayload) GetContactSignature() []byte {
	if x != nil {
		return x.ContactSignature
	}
	return nil
}

// RejectPayload is the payload for REJECT.
type RejectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"` // Which stage the rejection occurred in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPayload) Reset() {
	*x = RejectPayload{}
	mi := &file_handshake_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPayload) ProtoMessage() {}

func (x *RejectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_handshake_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPayload.ProtoReflect.Descriptor instead.
func (*RejectPayload) Descriptor() ([]byte, []int) {
	return file_handshake_proto_rawDescGZIP(), []int{13}
}

func (x *RejectPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectPayload) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

var File_handshake_proto protoreflect.FileDescriptor

const file_handshake_proto_rawDesc = "" +
	"\n" +
	"\x0fhandshake.proto\x12\thandshake\"\x95\x01\n" +
	"\x11HandshakeEnvelope\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.handshake.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"l\n" +
	"\x19AttestationRequestPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\tR\tchallenge\"k\n" +
	"\x1aAttestationResponsePayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\"]\n" +
	"\x19VectorMatchRequestPayload\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12'\n" +
	"\x0fencrypted_monad\x18\x02 \x01(\fR\x0eencryptedMonad\"O\n" +
	"\x1aVectorMatchResponsePayload\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\"Y\n" +
	"\x19DealBreakerRequestPayload\x12<\n" +
	"\tquestions\x18\x01 \x03(\v2\x1e.handshake.DealBreakerQuestionR\tquestions\"Y\n" +
	"\x13DealBreakerQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\bR\x06answer\"t\n" +
	"\x1aDealBreakerResponsePayload\x126\n" +
	"\aanswers\x18\x01 \x03(\v2\x1c.handshake.DealBreakerAnswerR\aanswers\x12\x1e\n" +
	"\n" +
	"compatible\x18\x02 \x01(\bR\n" +
	"compatible\"L\n" +
	"\x11DealBreakerAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\bR\x06answer\"|\n" +
	"\x12ChatMessagePayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12+\n" +
	"\x11encrypted_content\x18\x02 \x01(\fR\x10encryptedContent\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\",\n" +
	"\x14UnmaskRequestPayload\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"k\n" +
	"\x15UnmaskResponsePayload\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x126\n" +
	"\bidentity\x18\x02 \x01(\v2\x1a.handshake.IdentityPayloadR\bidentity\"\x88\x02\n" +
	"\x0fIdentityPayload\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rsignal_number\x18\x03 \x01(\tR\fsignalNumber\x12\x1b\n" +
	"\tmatrix_id\x18\x04 \x01(\tR\bmatrixId\x12$\n" +
	"\x0epgp_public_key\x18\x05 \x01(\fR\fpgpPublicKey\x12'\n" +
	"\x0fpgp_fingerprint\x18\x06 \x01(\tR\x0epgpFingerprint\x12+\n" +
	"\x11contact_signature\x18\a \x01(\fR\x10contactSignature\"=\n" +
	"\rRejectPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage*\xef\x01\n" +
	"\vMessageType\x12\x17\n" +
	"\x13ATTESTATION_REQUEST\x10\x00\x12\x18\n" +
	"\x14ATTESTATION_RESPONSE\x10\x01\x12\x18\n" +
	"\x14VECTOR_MATCH_REQUEST\x10\x02\x12\x19\n" +
	"\x15VECTOR_MATCH_RESPONSE\x10\x03\x12\x17\n" +
	"\x13DEALBREAKER_REQUEST\x10\x04\x12\x18\n" +
	"\x14DEALBREAKER_RESPONSE\x10\x05\x12\x10\n" +
	"\fCHAT_MESSAGE\x10\x06\x12\x12\n" +
	"\x0eUNMASK_REQUEST\x10\a\x12\x13\n" +
	"\x0fUNMASK_RESPONSE\x10\b\x12\n" +
	"\n" +
	"\x06REJECT\x10\tB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_handshake_proto_rawDescOnce sync.Once
	file_handshake_proto_rawDescData []byte
)

func file_handshake_proto_rawDescGZIP() []byte {
	file_handshake_proto_rawDescOnce.Do(func() {
		file_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_handshake_proto_rawDesc), len(file_handshake_proto_rawDesc)))
	})
	return file_handshake_proto_rawDescData
}

var file_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_handshake_proto_goTypes = []any{
	(MessageType)(0),                   // 0: handshake.MessageType
	(*HandshakeEnvelope)(nil),          // 1: handshake.HandshakeEnvelope
	(*AttestationRequestPayload)(nil),  // 2: handshake.AttestationRequestPayload
	(*AttestationResponsePayload)(nil), // 3: handshake.AttestationResponsePayload
	(*VectorMatchRequestPayload)(nil),  // 4: handshake.VectorMatchRequestPayload
	(*VectorMatchResponsePayload)(nil), // 5: handshake.VectorMatchResponsePayload
	(*DealBreakerRequestPayload)(nil),  // 6: handshake.DealBreakerRequestPayload
	(*DealBreakerQuestion)(nil),        // 7: handshake.DealBreakerQuestion
	(*DealBreakerResponsePayload)(nil), // 8: handshake.DealBreakerResponsePayload
	(*DealBreakerAnswer)(nil),          // 9: handshake.DealBreakerAnswer
	(*ChatMessagePayload)(nil),         // 10: handshake.ChatMessagePayload
	(*UnmaskRequestPayload)(nil),       // 11: handshake.UnmaskRequestPayload
	(*UnmaskResponsePayload)(nil),      // 12: handshake.UnmaskResponsePayload
	(*IdentityPayload)(nil),            // 13: handshake.IdentityPayload
	(*RejectPayload)(nil),              // 14: handshake.RejectPayload
}
var file_handshake_proto_depIdxs = []int32{
	0,  // 0: handshake.HandshakeEnvelope.type:type_name -> handshake.MessageType
	7,  // 1: handshake.DealBreakerRequestPayload.questions:type_name -> handshake.DealBreakerQuestion
	9,  // 2: handshake.DealBreakerResponsePayload.answers:type_name -> handshake.DealBreakerAnswer
	13, // 3: handshake.UnmaskResponsePayload.identity:type_name -> handshake.IdentityPayload
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_handshake_proto_init() }
func file_handshake_proto_init() {
	if File_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_handshake_proto_rawDesc), len(file_handshake_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handshake_proto_goTypes,
		DependencyIndexes: file_handshake_proto_depIdxs,
		EnumInfos:         file_handshake_proto_enumTypes,
		MessageInfos:      file_handshake_proto_msgTypes,
	}.Build()
	File_handshake_proto = out.File
	file_handshake_proto_goTypes = nil
	file_handshake_proto_depIdxs = nil
}
