// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: monad.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMonadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonadRequest) Reset() {
	*x = GetMonadRequest{}
	mi := &file_monad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonadRequest) ProtoMessage() {}

func (x *GetMonadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonadRequest.ProtoReflect.Descriptor instead.
func (*GetMonadRequest) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{0}
}

type GetMonadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EncryptedMonad []byte                 `protobuf:"bytes,1,opt,name=encrypted_monad,json=encryptedMonad,proto3" json:"encrypted_monad,omitempty"`
	Version        int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdated    int64                  `protobuf:"varint,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"` // Unix timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMonadResponse) Reset() {
	*x = GetMonadResponse{}
	mi := &file_monad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonadResponse) ProtoMessage() {}

func (x *GetMonadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonadResponse.ProtoReflect.Descriptor instead.
func (*GetMonadResponse) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{1}
}

func (x *GetMonadResponse) GetEncryptedMonad() []byte {
	if x != nil {
		return x.EncryptedMonad
	}
	return nil
}

func (x *GetMonadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetMonadResponse) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

type WatchMonadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMonadRequest) Reset() {
	*x = WatchMonadRequest{}
	mi := &file_monad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMonadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMonadRequest) ProtoMessage() {}

func (x *WatchMonadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMonadRequest.ProtoReflect.Descriptor instead.
func (*WatchMonadRequest) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{2}
}

type MonadUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EncryptedMonad []byte                 `protobuf:"bytes,1,opt,name=encrypted_monad,json=encryptedMonad,proto3" json:"encrypted_monad,omitempty"`
	Version        int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonadUpdate) Reset() {
	*x = MonadUpdate{}
	mi := &file_monad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonadUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonadUpdate) ProtoMessage() {}

func (x *MonadUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonadUpdate.ProtoReflect.Descriptor instead.
func (*MonadUpdate) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{3}
}

func (x *MonadUpdate) GetEncryptedMonad() []byte {
	if x != nil {
		return x.EncryptedMonad
	}
	return nil
}

func (x *MonadUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MonadUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_monad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ready             bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	DocumentsIndexed  int64                  `protobuf:"varint,2,opt,name=documents_indexed,json=documentsIndexed,proto3" json:"documents_indexed,omitempty"`
	LastScanTimestamp int64                  `protobuf:"varint,3,opt,name=last_scan_timestamp,json=lastScanTimestamp,proto3" json:"last_scan_timestamp,omitempty"`
	State             string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // "idle", "scanning", "embedding"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_monad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_monad_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusResponse) GetDocumentsIndexed() int64 {
	if x != nil {
		return x.DocumentsIndexed
	}
	return 0
}

func (x *StatusResponse) GetLastScanTimestamp() int64 {
	if x != nil {
		return x.LastScanTimestamp
	}
	return 0
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_monad_proto protoreflect.FileDescriptor

const file_monad_proto_rawDesc = "" +
	"\n" +
	"\vmonad.proto\x12\x05monad\"\x11\n" +
	"\x0fGetMonadRequest\"x\n" +
	"\x10GetMonadResponse\x12'\n" +
	"\x0fencrypted_monad\x18\x01 \x01(\fR\x0eencryptedMonad\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12!\n" +
	"\flast_updated\x18\x03 \x01(\x03R\vlastUpdated\"\x13\n" +
	"\x11WatchMonadRequest\"n\n" +
	"\vMonadUpdate\x12'\n" +
	"\x0fencrypted_monad\x18\x01 \x01(\fR\x0eencryptedMonad\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x0f\n" +
	"\rStatusRequest\"\x99\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12+\n" +
	"\x11documents_indexed\x18\x02 \x01(\x03R\x10documentsIndexed\x12.\n" +
	"\x13last_scan_timestamp\x18\x03 \x01(\x03R\x11lastScanTimestamp\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state2\xbe\x01\n" +
	"\n" +
	"MonadStore\x12;\n" +
	"\bGetMonad\x12\x16.monad.GetMonadRequest\x1a\x17.monad.GetMonadResponse\x12<\n" +
	"\n" +
	"WatchMonad\x12\x18.monad.WatchMonadRequest\x1a\x12.monad.MonadUpdate0\x01\x125\n" +
	"\x06Status\x12\x14.monad.StatusRequest\x1a\x15.monad.StatusResponseB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_monad_proto_rawDescOnce sync.Once
	file_monad_proto_rawDescData []byte
)

func file_monad_proto_rawDescGZIP() []byte {
	file_monad_proto_rawDescOnce.Do(func() {
		file_monad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monad_proto_rawDesc), len(file_monad_proto_rawDesc)))
	})
	return file_monad_proto_rawDescData
}

var file_monad_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_monad_proto_goTypes = []any{
	(*GetMonadRequest)(nil),   // 0: monad.GetMonadRequest
	(*GetMonadResponse)(nil),  // 1: monad.GetMonadResponse
	(*WatchMonadRequest)(nil), // 2: monad.WatchMonadRequest
	(*MonadUpdate)(nil),       // 3: monad.MonadUpdate
	(*StatusRequest)(nil),     // 4: monad.StatusRequest
	(*StatusResponse)(nil),    // 5: monad.StatusResponse
}
var file_monad_proto_depIdxs = []int32{
	0, // 0: monad.MonadStore.GetMonad:input_type -> monad.GetMonadRequest
	2, // 1: monad.MonadStore.WatchMonad:input_type -> monad.WatchMonadRequest
	4, // 2: monad.MonadStore.Status:input_type -> monad.StatusRequest
	1, // 3: monad.MonadStore.GetMonad:output_type -> monad.GetMonadResponse
	3, // 4: monad.MonadStore.WatchMonad:output_type -> monad.MonadUpdate
	5, // 5: monad.MonadStore.Status:output_type -> monad.StatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_monad_proto_init() }
func file_monad_proto_init() {
	if File_monad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monad_proto_rawDesc), len(file_monad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monad_proto_goTypes,
		DependencyIndexes: file_monad_proto_depIdxs,
		MessageInfos:      file_monad_proto_msgTypes,
	}.Build()
	File_monad_proto = out.File
	file_monad_proto_goTypes = nil
	file_monad_proto_depIdxs = nil
}
