// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: monad.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonadStore_GetMonad_FullMethodName   = "/monad.MonadStore/GetMonad"
	MonadStore_WatchMonad_FullMethodName = "/monad.MonadStore/WatchMonad"
	MonadStore_Status_FullMethodName     = "/monad.MonadStore/Status"
)

// MonadStoreClient is the client API for MonadStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonadStore is the IPC service exposed by the Ingestion Daemon.
type MonadStoreClient interface {
	// GetMonad returns the current encrypted Monad.
	GetMonad(ctx context.Context, in *GetMonadRequest, opts ...grpc.CallOption) (*GetMonadResponse, error)
	// WatchMonad streams updates when the Monad changes.
	WatchMonad(ctx context.Context, in *WatchMonadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonadUpdate], error)
	// Status returns the ingestion daemon status.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type monadStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewMonadStoreClient(cc grpc.ClientConnInterface) MonadStoreClient {
	return &monadStoreClient{cc}
}

func (c *monadStoreClient) GetMonad(ctx context.Context, in *GetMonadRequest, opts ...grpc.CallOption) (*GetMonadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonadResponse)
	err := c.cc.Invoke(ctx, MonadStore_GetMonad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monadStoreClient) WatchMonad(ctx context.Context, in *WatchMonadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonadUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonadStore_ServiceDesc.Streams[0], MonadStore_WatchMonad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMonadRequest, MonadUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonadStore_WatchMonadClient = grpc.ServerStreamingClient[MonadUpdate]

func (c *monadStoreClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MonadStore_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonadStoreServer is the server API for MonadStore service.
// All implementations must embed UnimplementedMonadStoreServer
// for forward compatibility.
//
// MonadStore is the IPC service exposed by the Ingestion Daemon.
type MonadStoreServer interface {
	// GetMonad returns the current encrypted Monad.
	GetMonad(context.Context, *GetMonadRequest) (*GetMonadResponse, error)
	// WatchMonad streams updates when the Monad changes.
	WatchMonad(*WatchMonadRequest, grpc.ServerStreamingServer[MonadUpdate]) error
	// Status returns the ingestion daemon status.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedMonadStoreServer()
}

// UnimplementedMonadStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonadStoreServer struct{}

func (UnimplementedMonadStoreServer) GetMonad(context.Context, *GetMonadRequest) (*GetMonadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonad not implemented")
}
func (UnimplementedMonadStoreServer) WatchMonad(*WatchMonadRequest, grpc.ServerStreamingServer[MonadUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchMonad not implemented")
}
func (UnimplementedMonadStoreServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMonadStoreServer) mustEmbedUnimplementedMonadStoreServer() {}
func (UnimplementedMonadStoreServer) testEmbeddedByValue()                    {}

// UnsafeMonadStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonadStoreServer will
// result in compilation errors.
type UnsafeMonadStoreServer interface {
	mustEmbedUnimplementedMonadStoreServer()
}

func RegisterMonadStoreServer(s grpc.ServiceRegistrar, srv MonadStoreServer) {
	// If the following call panics, it indicates UnimplementedMonadStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonadStore_ServiceDesc, srv)
}

func _MonadStore_GetMonad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadStoreServer).GetMonad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadStore_GetMonad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadStoreServer).GetMonad(ctx, req.(*GetMonadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonadStore_WatchMonad_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMonadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonadStoreServer).WatchMonad(m, &grpc.GenericServerStream[WatchMonadRequest, MonadUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonadStore_WatchMonadServer = grpc.ServerStreamingServer[MonadUpdate]

func _MonadStore_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadStoreServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadStore_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadStoreServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonadStore_ServiceDesc is the grpc.ServiceDesc for MonadStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonadStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monad.MonadStore",
	HandlerType: (*MonadStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonad",
			Handler:    _MonadStore_GetMonad_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MonadStore_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMonad",
			Handler:       _MonadStore_WatchMonad_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monad.proto",
}

const (
	AgentService_Status_FullMethodName           = "/monad.AgentService/Status"
	AgentService_Peers_FullMethodName            = "/monad.AgentService/Peers"
	AgentService_Bootstrap_FullMethodName        = "/monad.AgentService/Bootstrap"
	AgentService_Identity_FullMethodName         = "/monad.AgentService/Identity"
	AgentService_StartHandshake_FullMethodName   = "/monad.AgentService/StartHandshake"
	AgentService_ListHandshakes_FullMethodName   = "/monad.AgentService/ListHandshakes"
	AgentService_GetHandshake_FullMethodName     = "/monad.AgentService/GetHandshake"
	AgentService_ApproveHandshake_FullMethodName = "/monad.AgentService/ApproveHandshake"
	AgentService_RejectHandshake_FullMethodName  = "/monad.AgentService/RejectHandshake"
	AgentService_WatchHandshakes_FullMethodName  = "/monad.AgentService/WatchHandshakes"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the IPC service exposed by the Agent Daemon.
type AgentServiceClient interface {
	// Status returns the agent's current status.
	Status(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error)
	// Peers returns connected peers.
	Peers(ctx context.Context, in *PeersRequest, opts ...grpc.CallOption) (*PeersResponse, error)
	// Bootstrap manually connects to a peer.
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error)
	// Identity returns the local identity info.
	Identity(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error)
	// Handshake operations
	StartHandshake(ctx context.Context, in *StartHandshakeRequest, opts ...grpc.CallOption) (*StartHandshakeResponse, error)
	ListHandshakes(ctx context.Context, in *ListHandshakesRequest, opts ...grpc.CallOption) (*ListHandshakesResponse, error)
	GetHandshake(ctx context.Context, in *GetHandshakeRequest, opts ...grpc.CallOption) (*GetHandshakeResponse, error)
	ApproveHandshake(ctx context.Context, in *ApproveHandshakeRequest, opts ...grpc.CallOption) (*ApproveHandshakeResponse, error)
	RejectHandshake(ctx context.Context, in *RejectHandshakeRequest, opts ...grpc.CallOption) (*RejectHandshakeResponse, error)
	WatchHandshakes(ctx context.Context, in *WatchHandshakesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandshakeEvent], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Status(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*AgentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Peers(ctx context.Context, in *PeersRequest, opts ...grpc.CallOption) (*PeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeersResponse)
	err := c.cc.Invoke(ctx, AgentService_Peers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*BootstrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapResponse)
	err := c.cc.Invoke(ctx, AgentService_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Identity(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityResponse)
	err := c.cc.Invoke(ctx, AgentService_Identity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartHandshake(ctx context.Context, in *StartHandshakeRequest, opts ...grpc.CallOption) (*StartHandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartHandshakeResponse)
	err := c.cc.Invoke(ctx, AgentService_StartHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListHandshakes(ctx context.Context, in *ListHandshakesRequest, opts ...grpc.CallOption) (*ListHandshakesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHandshakesResponse)
	err := c.cc.Invoke(ctx, AgentService_ListHandshakes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetHandshake(ctx context.Context, in *GetHandshakeRequest, opts ...grpc.CallOption) (*GetHandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHandshakeResponse)
	err := c.cc.Invoke(ctx, AgentService_GetHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ApproveHandshake(ctx context.Context, in *ApproveHandshakeRequest, opts ...grpc.CallOption) (*ApproveHandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveHandshakeResponse)
	err := c.cc.Invoke(ctx, AgentService_ApproveHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RejectHandshake(ctx context.Context, in *RejectHandshakeRequest, opts ...grpc.CallOption) (*RejectHandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectHandshakeResponse)
	err := c.cc.Invoke(ctx, AgentService_RejectHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) WatchHandshakes(ctx context.Context, in *WatchHandshakesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HandshakeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_WatchHandshakes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchHandshakesRequest, HandshakeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchHandshakesClient = grpc.ServerStreamingClient[HandshakeEvent]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the IPC service exposed by the Agent Daemon.
type AgentServiceServer interface {
	// Status returns the agent's current status.
	Status(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error)
	// Peers returns connected peers.
	Peers(context.Context, *PeersRequest) (*PeersResponse, error)
	// Bootstrap manually connects to a peer.
	Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error)
	// Identity returns the local identity info.
	Identity(context.Context, *IdentityRequest) (*IdentityResponse, error)
	// Handshake operations
	StartHandshake(context.Context, *StartHandshakeRequest) (*StartHandshakeResponse, error)
	ListHandshakes(context.Context, *ListHandshakesRequest) (*ListHandshakesResponse, error)
	GetHandshake(context.Context, *GetHandshakeRequest) (*GetHandshakeResponse, error)
	ApproveHandshake(context.Context, *ApproveHandshakeRequest) (*ApproveHandshakeResponse, error)
	RejectHandshake(context.Context, *RejectHandshakeRequest) (*RejectHandshakeResponse, error)
	WatchHandshakes(*WatchHandshakesRequest, grpc.ServerStreamingServer[HandshakeEvent]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Status(context.Context, *AgentStatusRequest) (*AgentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAgentServiceServer) Peers(context.Context, *PeersRequest) (*PeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Peers not implemented")
}
func (UnimplementedAgentServiceServer) Bootstrap(context.Context, *BootstrapRequest) (*BootstrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedAgentServiceServer) Identity(context.Context, *IdentityRequest) (*IdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Identity not implemented")
}
func (UnimplementedAgentServiceServer) StartHandshake(context.Context, *StartHandshakeRequest) (*StartHandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartHandshake not implemented")
}
func (UnimplementedAgentServiceServer) ListHandshakes(context.Context, *ListHandshakesRequest) (*ListHandshakesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHandshakes not implemented")
}
func (UnimplementedAgentServiceServer) GetHandshake(context.Context, *GetHandshakeRequest) (*GetHandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHandshake not implemented")
}
func (UnimplementedAgentServiceServer) ApproveHandshake(context.Context, *ApproveHandshakeRequest) (*ApproveHandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveHandshake not implemented")
}
func (UnimplementedAgentServiceServer) RejectHandshake(context.Context, *RejectHandshakeRequest) (*RejectHandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectHandshake not implemented")
}
func (UnimplementedAgentServiceServer) WatchHandshakes(*WatchHandshakesRequest, grpc.ServerStreamingServer[HandshakeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchHandshakes not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Status(ctx, req.(*AgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Peers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Peers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Peers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Peers(ctx, req.(*PeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Identity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Identity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Identity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Identity(ctx, req.(*IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartHandshake(ctx, req.(*StartHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListHandshakes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHandshakesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListHandshakes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListHandshakes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListHandshakes(ctx, req.(*ListHandshakesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetHandshake(ctx, req.(*GetHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ApproveHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ApproveHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ApproveHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ApproveHandshake(ctx, req.(*ApproveHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RejectHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectHandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RejectHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RejectHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RejectHandshake(ctx, req.(*RejectHandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_WatchHandshakes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchHandshakesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).WatchHandshakes(m, &grpc.GenericServerStream[WatchHandshakesRequest, HandshakeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_WatchHandshakesServer = grpc.ServerStreamingServer[HandshakeEvent]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monad.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _AgentService_Status_Handler,
		},
		{
			MethodName: "Peers",
			Handler:    _AgentService_Peers_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _AgentService_Bootstrap_Handler,
		},
		{
			MethodName: "Identity",
			Handler:    _AgentService_Identity_Handler,
		},
		{
			MethodName: "StartHandshake",
			Handler:    _AgentService_StartHandshake_Handler,
		},
		{
			MethodName: "ListHandshakes",
			Handler:    _AgentService_ListHandshakes_Handler,
		},
		{
			MethodName: "GetHandshake",
			Handler:    _AgentService_GetHandshake_Handler,
		},
		{
			MethodName: "ApproveHandshake",
			Handler:    _AgentService_ApproveHandshake_Handler,
		},
		{
			MethodName: "RejectHandshake",
			Handler:    _AgentService_RejectHandshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHandshakes",
			Handler:       _AgentService_WatchHandshakes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monad.proto",
}
