// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.13.0
// source: monad.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonadStore_GetMonad_FullMethodName   = "/monad.MonadStore/GetMonad"
	MonadStore_WatchMonad_FullMethodName = "/monad.MonadStore/WatchMonad"
	MonadStore_Status_FullMethodName     = "/monad.MonadStore/Status"
)

// MonadStoreClient is the client API for MonadStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonadStore is the IPC service exposed by the Ingestion Daemon.
type MonadStoreClient interface {
	// GetMonad returns the current encrypted Monad.
	GetMonad(ctx context.Context, in *GetMonadRequest, opts ...grpc.CallOption) (*GetMonadResponse, error)
	// WatchMonad streams updates when the Monad changes.
	WatchMonad(ctx context.Context, in *WatchMonadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonadUpdate], error)
	// Status returns the ingestion daemon status.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type monadStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewMonadStoreClient(cc grpc.ClientConnInterface) MonadStoreClient {
	return &monadStoreClient{cc}
}

func (c *monadStoreClient) GetMonad(ctx context.Context, in *GetMonadRequest, opts ...grpc.CallOption) (*GetMonadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonadResponse)
	err := c.cc.Invoke(ctx, MonadStore_GetMonad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monadStoreClient) WatchMonad(ctx context.Context, in *WatchMonadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonadUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonadStore_ServiceDesc.Streams[0], MonadStore_WatchMonad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMonadRequest, MonadUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonadStore_WatchMonadClient = grpc.ServerStreamingClient[MonadUpdate]

func (c *monadStoreClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MonadStore_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonadStoreServer is the server API for MonadStore service.
// All implementations must embed UnimplementedMonadStoreServer
// for forward compatibility.
//
// MonadStore is the IPC service exposed by the Ingestion Daemon.
type MonadStoreServer interface {
	// GetMonad returns the current encrypted Monad.
	GetMonad(context.Context, *GetMonadRequest) (*GetMonadResponse, error)
	// WatchMonad streams updates when the Monad changes.
	WatchMonad(*WatchMonadRequest, grpc.ServerStreamingServer[MonadUpdate]) error
	// Status returns the ingestion daemon status.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedMonadStoreServer()
}

// UnimplementedMonadStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonadStoreServer struct{}

func (UnimplementedMonadStoreServer) GetMonad(context.Context, *GetMonadRequest) (*GetMonadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonad not implemented")
}
func (UnimplementedMonadStoreServer) WatchMonad(*WatchMonadRequest, grpc.ServerStreamingServer[MonadUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchMonad not implemented")
}
func (UnimplementedMonadStoreServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedMonadStoreServer) mustEmbedUnimplementedMonadStoreServer() {}
func (UnimplementedMonadStoreServer) testEmbeddedByValue()                    {}

// UnsafeMonadStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonadStoreServer will
// result in compilation errors.
type UnsafeMonadStoreServer interface {
	mustEmbedUnimplementedMonadStoreServer()
}

func RegisterMonadStoreServer(s grpc.ServiceRegistrar, srv MonadStoreServer) {
	// If the following call panics, it indicates UnimplementedMonadStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonadStore_ServiceDesc, srv)
}

func _MonadStore_GetMonad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadStoreServer).GetMonad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadStore_GetMonad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadStoreServer).GetMonad(ctx, req.(*GetMonadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonadStore_WatchMonad_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMonadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonadStoreServer).WatchMonad(m, &grpc.GenericServerStream[WatchMonadRequest, MonadUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonadStore_WatchMonadServer = grpc.ServerStreamingServer[MonadUpdate]

func _MonadStore_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadStoreServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadStore_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadStoreServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonadStore_ServiceDesc is the grpc.ServiceDesc for MonadStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonadStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monad.MonadStore",
	HandlerType: (*MonadStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonad",
			Handler:    _MonadStore_GetMonad_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MonadStore_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMonad",
			Handler:       _MonadStore_WatchMonad_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monad.proto",
}
