// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PoWChallenge is sent by the verifier to the prover during Stage 1 (Attestation).
// The challenge parameters are determined by the load-adaptive difficulty controller.
type PoWChallenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Random server nonce (16 bytes)
	// Used to bind the challenge to this specific request and prevent precomputation
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Unix milliseconds when the challenge was created
	// Challenges expire after a configured timeout (typically 30 seconds)
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Required number of leading zero bits in the solution hash
	// Valid values: 16 (easy), 20 (normal), 24 (hard), 28 (very hard)
	// Higher values require exponentially more computation
	Difficulty uint32 `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	// Verifier's libp2p peer ID
	// Binds the challenge to this specific verifier, preventing relay attacks
	PeerId        []byte `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoWChallenge) Reset() {
	*x = PoWChallenge{}
	mi := &file_pow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoWChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoWChallenge) ProtoMessage() {}

func (x *PoWChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_pow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoWChallenge.ProtoReflect.Descriptor instead.
func (*PoWChallenge) Descriptor() ([]byte, []int) {
	return file_pow_proto_rawDescGZIP(), []int{0}
}

func (x *PoWChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PoWChallenge) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PoWChallenge) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *PoWChallenge) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

// PoWSolution is sent by the prover in response to a PoWChallenge.
// The prover must find a counter value that produces a hash with sufficient leading zeros.
type PoWSolution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of the challenge nonce
	// Must match the nonce from the original challenge
	ChallengeNonce []byte `protobuf:"bytes,1,opt,name=challenge_nonce,json=challengeNonce,proto3" json:"challenge_nonce,omitempty"`
	// Echo of the challenge timestamp
	// Must match the timestamp from the original challenge
	ChallengeTimestamp int64 `protobuf:"varint,2,opt,name=challenge_timestamp,json=challengeTimestamp,proto3" json:"challenge_timestamp,omitempty"`
	// Counter value that produces a valid hash
	// The prover increments this until SHA-256(nonce || timestamp || peer_id || counter)
	// has the required number of leading zero bits
	Counter uint64 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	// The computed proof: SHA-256(nonce || timestamp || peer_id || counter)
	// Must have at least 'difficulty' leading zero bits (32 bytes)
	Proof         []byte `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoWSolution) Reset() {
	*x = PoWSolution{}
	mi := &file_pow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoWSolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoWSolution) ProtoMessage() {}

func (x *PoWSolution) ProtoReflect() protoreflect.Message {
	mi := &file_pow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoWSolution.ProtoReflect.Descriptor instead.
func (*PoWSolution) Descriptor() ([]byte, []int) {
	return file_pow_proto_rawDescGZIP(), []int{1}
}

func (x *PoWSolution) GetChallengeNonce() []byte {
	if x != nil {
		return x.ChallengeNonce
	}
	return nil
}

func (x *PoWSolution) GetChallengeTimestamp() int64 {
	if x != nil {
		return x.ChallengeTimestamp
	}
	return 0
}

func (x *PoWSolution) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *PoWSolution) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// PoWResult indicates the verification outcome of a PoWSolution.
// Sent by the verifier to inform the prover whether the solution was accepted.
type PoWResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the solution is valid and the prover may proceed
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Error code if validation failed. Possible values:
	// - "expired": Challenge timestamp is too old (> configured timeout)
	// - "invalid_nonce": Challenge nonce doesn't match any pending challenge
	// - "insufficient_difficulty": Solution doesn't meet required difficulty
	// - "hash_mismatch": Proof doesn't match SHA-256(nonce || timestamp || peer_id || counter)
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoWResult) Reset() {
	*x = PoWResult{}
	mi := &file_pow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoWResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoWResult) ProtoMessage() {}

func (x *PoWResult) ProtoReflect() protoreflect.Message {
	mi := &file_pow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoWResult.ProtoReflect.Descriptor instead.
func (*PoWResult) Descriptor() ([]byte, []int) {
	return file_pow_proto_rawDescGZIP(), []int{2}
}

func (x *PoWResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *PoWResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pow_proto protoreflect.FileDescriptor

const file_pow_proto_rawDesc = "" +
	"\n" +
	"\tpow.proto\x12\vmymonad.pow\"{\n" +
	"\fPoWChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\rR\n" +
	"difficulty\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\fR\x06peerId\"\x97\x01\n" +
	"\vPoWSolution\x12'\n" +
	"\x0fchallenge_nonce\x18\x01 \x01(\fR\x0echallengeNonce\x12/\n" +
	"\x13challenge_timestamp\x18\x02 \x01(\x03R\x12challengeTimestamp\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x04R\acounter\x12\x14\n" +
	"\x05proof\x18\x04 \x01(\fR\x05proof\"7\n" +
	"\tPoWResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_pow_proto_rawDescOnce sync.Once
	file_pow_proto_rawDescData []byte
)

func file_pow_proto_rawDescGZIP() []byte {
	file_pow_proto_rawDescOnce.Do(func() {
		file_pow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pow_proto_rawDesc), len(file_pow_proto_rawDesc)))
	})
	return file_pow_proto_rawDescData
}

var file_pow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pow_proto_goTypes = []any{
	(*PoWChallenge)(nil), // 0: mymonad.pow.PoWChallenge
	(*PoWSolution)(nil),  // 1: mymonad.pow.PoWSolution
	(*PoWResult)(nil),    // 2: mymonad.pow.PoWResult
}
var file_pow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pow_proto_init() }
func file_pow_proto_init() {
	if File_pow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pow_proto_rawDesc), len(file_pow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pow_proto_goTypes,
		DependencyIndexes: file_pow_proto_depIdxs,
		MessageInfos:      file_pow_proto_msgTypes,
	}.Build()
	File_pow_proto = out.File
	file_pow_proto_goTypes = nil
	file_pow_proto_depIdxs = nil
}
