// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: zkproof.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ZKProofRequest initiates a ZK proof exchange between two peers.
// The requester sends their commitment and revealed signature, and the responder
// must generate a proof that their (hidden) signature is within the agreed Hamming
// distance threshold of the revealed signature.
type ZKProofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agreed Hamming distance threshold k
	// Both peers must agree on this value during capability negotiation.
	// The proof will verify that Hamming(sig_a, sig_b) <= max_distance.
	MaxDistance uint32 `protobuf:"varint,1,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	// MiMC commitment to the requester's LSH signature: MiMC(signature, salt)
	// This commitment is revealed later, allowing the responder to verify
	// that the requester didn't change their signature after seeing the response.
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// Requester's revealed LSH signature
	// The responder uses this as the public input to their ZK proof,
	// proving proximity to this signature without revealing their own.
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKProofRequest) Reset() {
	*x = ZKProofRequest{}
	mi := &file_zkproof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKProofRequest) ProtoMessage() {}

func (x *ZKProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zkproof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKProofRequest.ProtoReflect.Descriptor instead.
func (*ZKProofRequest) Descriptor() ([]byte, []int) {
	return file_zkproof_proto_rawDescGZIP(), []int{0}
}

func (x *ZKProofRequest) GetMaxDistance() uint32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

func (x *ZKProofRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *ZKProofRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ZKProofResponse contains the ZK proof and the responder's commitment.
// After receiving a ZKProofRequest, the responder generates a PLONK proof
// demonstrating their signature is within the Hamming threshold.
type ZKProofResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized PLONK proof (gnark bn254 format)
	// The proof demonstrates: "I know a signature S such that
	// Hamming(S, requester_signature) <= max_distance AND
	// MiMC(S, salt) = my_commitment"
	Proof []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	// MiMC commitment to the responder's LSH signature
	// Used by the requester to verify the proof binds to the responder's signature
	Commitment []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// Responder's revealed LSH signature
	// Revealed for mutual verification - the requester can now prove
	// proximity to this signature as well
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKProofResponse) Reset() {
	*x = ZKProofResponse{}
	mi := &file_zkproof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKProofResponse) ProtoMessage() {}

func (x *ZKProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zkproof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKProofResponse.ProtoReflect.Descriptor instead.
func (*ZKProofResponse) Descriptor() ([]byte, []int) {
	return file_zkproof_proto_rawDescGZIP(), []int{1}
}

func (x *ZKProofResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ZKProofResponse) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *ZKProofResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ZKProofResult indicates the verification outcome of a ZKProofResponse.
// Sent after verifying the proof to inform the peer of the result.
type ZKProofResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the proof verified successfully
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Error code if validation failed. Possible values:
	// - "invalid_proof": The PLONK proof failed verification
	// - "commitment_mismatch": The proof commitment doesn't match the advertised commitment
	// - "threshold_exceeded": The Hamming distance exceeds the agreed threshold
	// - "malformed_proof": The proof bytes could not be deserialized
	// - "invalid_signature": The signature has incorrect length or format
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKProofResult) Reset() {
	*x = ZKProofResult{}
	mi := &file_zkproof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKProofResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKProofResult) ProtoMessage() {}

func (x *ZKProofResult) ProtoReflect() protoreflect.Message {
	mi := &file_zkproof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKProofResult.ProtoReflect.Descriptor instead.
func (*ZKProofResult) Descriptor() ([]byte, []int) {
	return file_zkproof_proto_rawDescGZIP(), []int{2}
}

func (x *ZKProofResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ZKProofResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ZKCapability advertises a peer's support for ZK proofs in DHT bucket records.
// Peers discover each other's capabilities during DHT lookups and use this
// information to determine protocol compatibility before initiating exchanges.
type ZKCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the peer supports ZK proof verification
	// Peers should only attempt ZK exchanges with compatible peers
	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	// Proof system identifier for compatibility checking
	// Currently only "plonk-bn254" is supported
	// Future versions may support "groth16-bn254", "plonk-bls12", etc.
	ProofSystem string `protobuf:"bytes,2,opt,name=proof_system,json=proofSystem,proto3" json:"proof_system,omitempty"`
	// Maximum LSH signature length this peer can handle (in bits)
	// Typically 256 bits. Peers must have matching signature lengths
	// to generate/verify compatible proofs.
	MaxSignatureBits uint32 `protobuf:"varint,3,opt,name=max_signature_bits,json=maxSignatureBits,proto3" json:"max_signature_bits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ZKCapability) Reset() {
	*x = ZKCapability{}
	mi := &file_zkproof_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKCapability) ProtoMessage() {}

func (x *ZKCapability) ProtoReflect() protoreflect.Message {
	mi := &file_zkproof_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKCapability.ProtoReflect.Descriptor instead.
func (*ZKCapability) Descriptor() ([]byte, []int) {
	return file_zkproof_proto_rawDescGZIP(), []int{3}
}

func (x *ZKCapability) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *ZKCapability) GetProofSystem() string {
	if x != nil {
		return x.ProofSystem
	}
	return ""
}

func (x *ZKCapability) GetMaxSignatureBits() uint32 {
	if x != nil {
		return x.MaxSignatureBits
	}
	return 0
}

var File_zkproof_proto protoreflect.FileDescriptor

const file_zkproof_proto_rawDesc = "" +
	"\n" +
	"\rzkproof.proto\x12\x0fmymonad.zkproof\"q\n" +
	"\x0eZKProofRequest\x12!\n" +
	"\fmax_distance\x18\x01 \x01(\rR\vmaxDistance\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fR\n" +
	"commitment\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"e\n" +
	"\x0fZKProofResponse\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fR\n" +
	"commitment\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\";\n" +
	"\rZKProofResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"}\n" +
	"\fZKCapability\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12!\n" +
	"\fproof_system\x18\x02 \x01(\tR\vproofSystem\x12,\n" +
	"\x12max_signature_bits\x18\x03 \x01(\rR\x10maxSignatureBitsB&Z$github.com/mymonad/mymonad/api/protob\x06proto3"

var (
	file_zkproof_proto_rawDescOnce sync.Once
	file_zkproof_proto_rawDescData []byte
)

func file_zkproof_proto_rawDescGZIP() []byte {
	file_zkproof_proto_rawDescOnce.Do(func() {
		file_zkproof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zkproof_proto_rawDesc), len(file_zkproof_proto_rawDesc)))
	})
	return file_zkproof_proto_rawDescData
}

var file_zkproof_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zkproof_proto_goTypes = []any{
	(*ZKProofRequest)(nil),  // 0: mymonad.zkproof.ZKProofRequest
	(*ZKProofResponse)(nil), // 1: mymonad.zkproof.ZKProofResponse
	(*ZKProofResult)(nil),   // 2: mymonad.zkproof.ZKProofResult
	(*ZKCapability)(nil),    // 3: mymonad.zkproof.ZKCapability
}
var file_zkproof_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zkproof_proto_init() }
func file_zkproof_proto_init() {
	if File_zkproof_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zkproof_proto_rawDesc), len(file_zkproof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zkproof_proto_goTypes,
		DependencyIndexes: file_zkproof_proto_depIdxs,
		MessageInfos:      file_zkproof_proto_msgTypes,
	}.Build()
	File_zkproof_proto = out.File
	file_zkproof_proto_goTypes = nil
	file_zkproof_proto_depIdxs = nil
}
